-- 가입 정보
CREATE TABLE TAB_ORGAN ( 
	NUM_OID			NUMBER(8),				-- 학교 일련번호
	STR_DIR			VARCHAR2(50) NOT NULL,			-- 저장될 디렉토리명
	CHR_USE_INTRO		CHAR(1) DEFAULT 'Y' NOT NULL,		-- (추가) 인트로 사용여부
	STR_URL 		VARCHAR2(100),				-- 학교 url
	STR_TYPE 		VARCHAR(30) DEFAULT 'A' NOT NULL,	-- 스킨 타입
	STR_THEME 		VARCHAR(30) DEFAULT 'A' NOT NULL,	-- 디자인 테마(시리즈,세트) ! 타잎별로 사용할 수 있는 테마가 따로 있음
	NUM_HDD			NUMBER(8) DEFAULT '100' NOT NULL,	-- 허용용량
	STR_TITLE		VARCHAR2(30) NOT NULL,			-- 학교명
	STR_CEO_NAME		VARCHAR2(16) NOT NULL,			-- 교장 이름
	STR_CEO_EMAIL		VARCHAR2(30),				-- 교장 이메일
	STR_TEL			VARCHAR2(14) NOT NULL,			-- 학교 전화번호
	STR_FAX			VARCHAR2(14),				-- 학교 팩스번호
	CHR_ZIP			CHAR(7) NOT NULL,			-- 학교 우편번호
	STR_ADDR		VARCHAR2(250) NOT NULL,			-- 학교 주소
	STR_MASTER_NAME		VARCHAR2(16) NOT NULL,			-- 관리자 이름
	STR_MASTER_PHONE	VARCHAR2(14) NOT NULL,			-- 관리자 전화번호
	STR_MASTER_MOBILE	VARCHAR2(14),				-- 관리자 핸드폰번호
	STR_MASTER_EMAIL	VARCHAR2(30),				-- 관리자 이메일
	STR_PASSWORD		VARCHAR2(8) NOT NULL,			-- 학교 비밀번호
	DT_ENTER_DAY		DATE DEFAULT SYSDATE,			-- 개설일자
	DT_EXPIRES_DAY		DATE,					-- (추가) 만료일자

	CONSTRAINT PK_TAB_ORGAN
	PRIMARY KEY (NUM_OID)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;


CREATE TABLE TAB_MENU( 
	NUM_OID		NUMBER(8) NOT NULL,				-- 학교 일련번호
	NUM_STEP	NUMBER(8) DEFAULT 1 NOT NULL,			-- 메뉴 순서
	NUM_MCODE	NUMBER(8) DEFAULT 1 NOT NULL,			-- 메뉴 일련번호
	STR_TITLE	VARCHAR2(30) NOT NULL,				-- 메뉴 명
	CHR_TYPE	CHAR(1) DEFAULT 'A' NOT NULL,			-- 메뉴 타입(갤러리, 게시판 등등 )

	CONSTRAINT PK_TAB_MENU
	PRIMARY KEY (NUM_OID,NUM_STEP,NUM_MCODE)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;


-- 
-- 회원
-- 
CREATE TABLE TAB_MEMBER(
	NUM_OID		NUMBER(8) NOT NULL,				-- 학교생성 일련번호
	STR_ID		VARCHAR2(15) NOT NULL,				-- TBL_EWUT_MEMBER's STR_ID
	CHR_MEMTYPE	CHAR(1) NOT NULL,				-- 회원구분( t 선생님 )
	STR_IP		VARCHAR2(15) NOT NULL,				-- 가입당시 아이피
	DT_DATE		DATE DEFAULT SYSDATE NOT NULL,			-- 등록일
	CHR_AUTH	CHAR(1) DEFAULT 'N' NOT NULL,			-- 인증여부
	NUM_LEVEL	NUMBER(8) DEFAULT 0 NOT NULL,			-- 회원레벨
	STR_NAME	VARCHAR2(20) NULL,				-- 회원이름
	
	CONSTRAINT PK_TAB_MEMBER
	PRIMARY KEY (NUM_OID,STR_ID,CHR_MEMTYPE)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

CREATE INDEX IDX_TAB_MEMBER
    ON TAB_MEMBER (NUM_OID,CHR_AUTH)
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 4096K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

CREATE INDEX IDX_TAB_MEMBER_NAME
    ON TAB_MEMBER  ( NUM_OID,STR_NAME,CHR_MEMTYPE )
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 1 MAXEXTENTS
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL KEEP)
    NOLOGGING ;

CREATE INDEX IDX_TAB_MEMBER_SEARCH_ONE
    ON TAB_MEMBER  ( NUM_OID,CHR_MEMTYPE,CHR_AUTH )
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 1 MAXEXTENTS
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL KEEP)
    NOLOGGING ;

CREATE INDEX IDX_TAB_MEMBER_SEARCH_LEVEL
    ON TAB_MEMBER  ( NUM_OID,CHR_MEMTYPE,NUM_LEVEL )
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 1 MAXEXTENTS
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL KEEP)
    NOLOGGING ;

-- 
-- 회원 레벨 정의
-- 
CREATE TABLE TAB_MEMBER_LEVEL(
	NUM_OID		NUMBER(8) NOT NULL,				-- 학교생성 일련번호
	NUM_LEVEL	NUMBER(8) NOT NULL,				-- 레벨
	STR_TITLE	NUMBER(8) NOT NULL,				-- 레벨이름

	CONSTRAINT PK_TAB_MEMBER_LEVEL
	PRIMARY KEY (NUM_OID,NUM_LEVEL,STR_TITLE)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

-- 
-- 컨텐츠 접근권한 설정
-- 
CREATE TABLE TAB_ACCESS_RIGHT(
	NUM_OID		NUMBER(8) NOT NULL,			-- 학교 일련번호
	STR_SECT	VARCHAR(20) NOT NULL,		-- "main" "menu" "ioffice" ...
	STR_CODE	VARCHAR(20) NOT NULL,		-- 메인 컨텐츠코드 또는 mcode ("a" "branch" ...)
	CHR_MEMTYPE	CHAR(1) NOT NULL,			-- 회원타잎 (s,p,t,g,n)
	NUM_LEVEL	NUMBER(8) DEFAULT 1 NOT NULL,			-- 최소 레벨
	CHR_RIGHT	CHAR(1) NOT NULL,			-- 권한( w - 쓰기, r - 읽기, x - 관리')

	CONSTRAINT PK_TAB_MAIN_RIGHT
	PRIMARY KEY (NUM_OID,CHR_MCODE,CHR_GROUP)
	USING INDEX
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

/*

// PERM->apply('r');
SELECT
	COUNT(*)
FROM
	TAB_ACCESS_RIGHT
WHERE
	num_oid={$oid} AND chr_sect='{$sect}' AND chr_code='{$code}' AND chr_right='r'



// insert 'rw-' perm S2
DELETE FROM
	TAB_ACCESS_RIGHT
WHERE
	num_oid={$oid} AND chr_sect='{$sect}' AND chr_code='{$code}' AND chr_memtype='s';

INSERT INTO TAB_ACCESS_RIGHT
	(num_oid,chr_sect,chr_code,chr_memtype,num_level,chr_right)
VALUES
	({$oid},'{$sect}','{$code}','s',2,'r');

INSERT INTO TAB_ACCESS_RIGHT
	(num_oid,chr_sect,chr_code,chr_memtype,num_level,chr_right)
VALUES
	({$oid},'{$sect}','{$code}','s',2,'w');
*/