-- 메뉴
CREATE TABLE TAB_MENU
(
	NUM_OID    NUMBER(8)			NOT NULL,
	NUM_STEP   NUMBER(8)			DEFAULT 1	NOT NULL,
	NUM_MCODE  NUMBER(8)			DEFAULT 1	NOT NULL,
	STR_TITLE  VARCHAR2(30)			NOT NULL,
	STR_TYPE   VARCHAR2(10)			DEFAULT 'A'	NOT NULL,

	CONSTRAINT PK_TAB_MENU
	PRIMARY KEY (NUM_OID,NUM_MCODE)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1M NEXT 1M) NOCACHE;


-- 공지사항
CREATE TABLE TAB_MAIN_BOARD(
	NUM_OID		NUMBER(8) NOT NULL,			-- 학교 일련번호
	STR_CODE	VARCHAR2(10) DEFAULT 'com' NOT NULL,	-- 어디 글인지 여부
	NUM_SERIAL	NUMBER(8) NOT NULL,			-- 일련번호
	STR_TITLE	VARCHAR2(60) NOT NULL,			-- 제목
	STR_TEXT1	VARCHAR2(4000) NOT NULL,		-- 내용
	STR_TEXT2	VARCHAR2(4000),				-- 내용
	STR_TEXT3	VARCHAR2(4000),				-- 내용
	CHR_HTML	CHAR(1) DEFAULT 'Y' NOT NULL,		-- HTML 사용여부
	DT_DATE		DATE DEFAULT SYSDATE,			-- 작성일자
	NUM_HIT		NUMBER(8) DEFAULT 0,			-- 조회수
	STR_THUMB	VARCHAR2(100),				-- 썸네일

	CONSTRAINT PK_TAB_MAIN_BOARD
	PRIMARY KEY (NUM_OID,STR_CODE,NUM_SERIAL)
	USING INDEX
	TABLESPACE TS_ACADEMY_D
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_I STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;

-- 팝업
CREATE TABLE TAB_POPUP( 
	NUM_OID		NUMBER(8) NOT NULL,			-- 학교 일련번호
	NUM_SERIAL	NUMBER(8) NOT NULL,			-- 팝업 테이블 일련번호
	STR_TITLE	VARCHAR2(60) NOT NULL,			-- 팝업제목
	STR_TEXT1	VARCHAR2(4000) NOT NULL,		-- 팝업내용
	STR_TEXT2	VARCHAR2(4000),				-- 팝업내용
	STR_TEXT3	VARCHAR2(4000),				-- 팝업내용
	CHR_SKIN	VARCHAR2(10) DEFAULT 'default',		-- 팝업창 디자인 타입
	STR_BG_UPFILE	VARCHAR2(100),
	STR_BG_REFILE	VARCHAR2(100),
	CHR_OPEN	CHAR(1) DEFAULT 'N',			-- 사용여부
	NUM_WIDTH	NUMBER(4) NOT NULL,			-- 창 가로 사이즈
	NUM_HEIGHT	NUMBER(4) NOT NULL,			-- 창 세로 사이즈
	NUM_LEFT	NUMBER(4) DEFAULT 0 NOT NULL,		-- 창 위치 (X 좌표)
	NUM_TOP		NUMBER(4) DEFAULT 0 NOT NULL,		-- 창 위치 (Y 좌표)
	DT_DATE		DATE DEFAULT SYSDATE,			-- 입력날짜

	CONSTRAINT PK_TAB_POPUP
	PRIMARY KEY (NUM_OID,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;

CREATE INDEX IDX_TAB_POPUP
    ON TAB_POPUP  (NUM_OID,CHR_OPEN) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

CREATE TABLE TAB_CALENDAR( 
	NUM_OID		NUMBER(8) NOT NULL,
	NUM_SERIAL	NUMBER(8) NOT NULL,
	STR_TITLE	VARCHAR2(150) NOT NULL,
	DT_DAYS		DATE DEFAULT SYSDATE,
	CHR_HTML	CHAR(1) DEFAULT 'Y',
	STR_TEXT	VARCHAR2(4000) NOT NULL,
	STR_LINK	VARCHAR2(150),
	NUM_ICON	NUMBER(2) NOT NULL,
	DT_DATE		DATE DEFAULT SYSDATE,
	NUM_HIT		NUMBER(3) DEFAULT 0,

	CONSTRAINT PK_TAB_CALENDAR
	PRIMARY KEY (NUM_OID,NUM_SERIAL,DT_DAYS)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;

CREATE INDEX IDX_TAB_CALENDAR_LIST
    ON TAB_CALENDAR (NUM_OID,DT_DAYS) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

-- 배너
CREATE TABLE TAB_BANNER(
	NUM_OID		NUMBER(8) NOT NULL,			-- 학교 일련번호
	NUM_SERIAL	NUMBER(8) NOT NULL,			-- 일련번호
	NUM_STEP	NUMBER(8) NOT NULL,			-- 표시순서
	STR_TITLE	VARCHAR2(50) NOT NULL,			-- 제목
	STR_LINK	VARCHAR2(100) NOT NULL,			-- URL ADDRESS
	CHR_OPEN	VARCHAR2(6) DEFAULT '_blank' NOT NULL,	-- 새창으로 띄울지, 현재창을 체인지 할지
	STR_FILE	VARCHAR2(100),			-- 이미지 파일 경로
	DT_DATE		DATE DEFAULT SYSDATE,

	CONSTRAINT PK_TAB_BANNER
	PRIMARY KEY (NUM_OID,NUM_SERIAL)
	USING INDEX
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;

CREATE INDEX IDX_TAB_BANNER
    ON TAB_BANNER (NUM_OID,NUM_STEP) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

-- 설문조사 메인

CREATE TABLE TAB_POLL_MAIN(
	NUM_OID			NUMBER(8) NOT NULL,			-- 학교 일련번호
	NUM_SERIAL		NUMBER(8) NOT NULL,			-- 설문 일련번호
	STR_SECT		VARCHAR2(10) DEFAULT 'main' NOT NULL,	-- 학교홈: main / 전자교무실 : ioffice 구분
	STR_TITLE		VARCHAR2(150) NOT NULL,			-- 설문 제목
	DT_START_DATE		DATE DEFAULT SYSDATE,			-- 설문 시작일
	DT_FINISH_DATE		DATE DEFAULT SYSDATE,			-- 설문 종료일
	CHR_CHECK		CHAR(2) DEFAULT 'ip' NOT NULL,		-- 중복 투표 방지 책 선택
	CHR_RESULT		CHAR(1) DEFAULT 'e' NOT NULL,		-- 결과를 언제 보여줄껀지 선택( e -> 진행중확인, i -> 종료 후 확인 )
	DT_DATE			DATE DEFAULT SYSDATE,			-- 등록일

	CONSTRAINT PK_TAB_POLL_MAIN
	PRIMARY KEY (NUM_OID,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
)TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

CREATE INDEX IDX_TAB_POLL_TERM
    ON TAB_POLL_MAIN (NUM_OID,STR_SECT,NUM_SERIAL,DT_START_DATE,DT_FINISH_DATE) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

-- 설문조사 항목

CREATE TABLE TAB_POLL_CONTENTS(
	NUM_OID			NUMBER(8) NOT NULL,		-- 학교 일련번호
	NUM_MAIN		NUMBER(8) NOT NULL,		-- 설문 일련번호
	NUM_SERIAL		NUMBER(8) NOT NULL,		-- 항목 일련번호
	STR_CONTENTS		VARCHAR2(150) NOT NULL,		-- 항목 내용
	NUM_VOTE		NUMBER(8) DEFAULT 0,		-- 투표수

	CONSTRAINT PK_TAB_POLL_CONTENTS
	PRIMARY KEY (NUM_OID,NUM_MAIN,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
)TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

-- 기투표자 아이피

CREATE TABLE TAB_POLL_IP(
	NUM_OID			NUMBER(8) NOT NULL,		-- 학교 일련번호
	NUM_MAIN		NUMBER(8) NOT NULL,		-- 설문 일련번호
	STR_IP			VARCHAR2(20) NOT NULL,		-- 투표자 아이피

	CONSTRAINT PK_TAB_POLL_IP
	PRIMARY KEY (NUM_OID,NUM_MAIN,STR_IP)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
)TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

-- 기투표자 아이디

CREATE TABLE TAB_POLL_USER(
	NUM_OID			NUMBER(8) NOT NULL,		-- 학교 일련번호
	NUM_MAIN		NUMBER(8) NOT NULL,		-- 설문 일련번호
	STR_USER		VARCHAR2(20) NOT NULL,		-- 투표자 아이디

	CONSTRAINT PK_TAB_POLL_USER
	PRIMARY KEY (NUM_OID,NUM_MAIN,STR_USER)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
)TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

-- 한줄글쓰기

CREATE TABLE TAB_POLL_COMMENT(
	NUM_OID			NUMBER(8) NOT NULL,		-- 학교 일련번호
	NUM_MAIN		NUMBER(8) NOT NULL,		-- 설문 일련번호
	NUM_SERIAL		NUMBER(8) NOT NULL,		-- 한줄 일련번호
	STR_COMMENT		VARCHAR2(100) NOT NULL,		-- 한줄 메모
	STR_ID			VARCHAR2(12),			-- 회원일 경우 아이디
	STR_NAME		VARCHAR2(16) NOT NULL,		-- 닉네임
	STR_PASS		VARCHAR2(10) NOT NULL,		-- 패스워드
	DT_DATE			DATE DEFAULT SYSDATE,		-- 한줄 메뉴 입력일자
	STR_IP			VARCHAR2(20) NOT NULL,		-- 메모자 아이피

	CONSTRAINT PK_TAB_POLL_COMMENT
	PRIMARY KEY (NUM_OID,NUM_MAIN,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
)TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;



--------------------------------------------------------------------------
-- 상담실 게시판
--------------------------------------------------------------------------

CREATE TABLE TAB_COUNCIL( 
	NUM_OID		NUMBER(8) NOT NULL,		-- 학교구분
	NUM_MCODE	NUMBER(8) NOT NULL,		-- 메뉴코드
	NUM_SERIAL	NUMBER(8) NOT NULL,		-- 글 번호
	NUM_GROUP	NUMBER(8) NOT NULL,		-- 글 그룹
	NUM_STEP	NUMBER(8) DEFAULT 0 NOT NULL,	-- 글 그룹 내의 순서
	NUM_DEPTH	NUMBER(1) DEFAULT 0 NOT NULL,	-- 글 그룹 내의 들여쓰기
	STR_USER	VARCHAR2(15),			-- 로그인 후 글쓸대 회원 아이디
	STR_OUSER	VARCHAR2(15),			-- 해당글의 소유자(원본글의 글쓴이 아이디)
	STR_NAME	VARCHAR2(20) NOT NULL,		-- 이름
	STR_EMAIL	VARCHAR2(30),			-- 이메일
	STR_TITLE	VARCHAR2(60) NOT NULL,		-- 제목
	STR_TEXT1	VARCHAR2(4000) NOT NULL,		-- 글 내용 첫번째
	STR_TEXT2	VARCHAR2(4000),			-- 글 내용 두번째
	STR_TEXT3	VARCHAR2(4000),			-- 글 내용 세번째
	CHR_HTML	CHAR(1) DEFAULT 'Y' NOT NULL,	-- HTML 사용여부
	DT_DATE		DATE DEFAULT SYSDATE,		-- 등록일자
	NUM_HIT		NUMBER(8) DEFAULT 0 NOT NULL,	-- 조회수
	NUM_FILE	NUMBER(2) DEFAULT 0 NOT NULL,	-- 파일개수 ( 파일의 갯수가 0일때 파일테이블을 CALL하지 않는다 )
	NUM_PUBLIC	NUMBER(1) DEFAULT 0 NOT NULL,	-- 공개여부
	CHR_METHOD	CHAR(1) DEFAULT 'B' NOT NULL,	-- 답변방법(B 게시판 답변 E 이메일 답변)
	STR_IP		VARCHAR2(15) NOT NULL,		-- 아이피

	CONSTRAINT PK_TAB_COUNCIL
	PRIMARY KEY (NUM_OID,NUM_MCODE,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 1024K NEXT 1024K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 10240K NEXT 10240K) NOCACHE;

CREATE INDEX IDX_TAB_COUNCIL_PUBLIC
    ON TAB_COUNCIL (NUM_OID,NUM_MCODE,NUM_DEPTH,NUM_PUBLIC,STR_OUSER) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

CREATE INDEX IDX_TAB_COUNCIL_SEARCH
    ON TAB_COUNCIL (NUM_OID,NUM_MCODE,NUM_GROUP,NUM_STEP,STR_NAME,STR_TITLE) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;


-- 게시판 설정

CREATE TABLE TAB_COUNCIL_CONFIG (
	NUM_OID		NUMBER(8) NOT NULL,			-- 학교구분
	NUM_MCODE	NUMBER(8) NOT NULL,			-- 메뉴코드
	STR_TITLE	VARCHAR2(50) DEFAULT '상담실' NOT NULL,	-- 게시판 타이틀
	STR_SKIN	VARCHAR2(20) DEFAULT 'default' NOT NULL,	-- 게시판 스킨
	NUM_LISTNUM	NUMBER(8) DEFAULT 10 NOT NULL,		-- 목록 표시줄수
	NUM_NAVNUM	NUMBER(8) DEFAULT 10 NOT NULL,		-- 페이징 표시갯수
	NUM_TITLELEN	NUMBER(8) DEFAULT 200 NOT NULL,		-- 타이틀바 길이(바이트)
	CHR_ODDCOLOR	CHAR(7) DEFAULT '#FFFFFF' NOT NULL,	-- 홀수열 색상
	CHR_EVENCOLOR	CHAR(7) DEFAULT '#FFFFFF' NOT NULL,	-- 짝수열 색상

	CONSTRAINT PK_TAB_COUNCIL_CONFIG
	PRIMARY KEY (NUM_OID,NUM_MCODE)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 2048K NEXT 2048K) NOCACHE;

--
-- 게시판
--

CREATE TABLE TAB_BOARD( 
	NUM_OID		NUMBER(8) NOT NULL,				-- 학교구분
	NUM_MCODE	NUMBER(8) NOT NULL,				-- 메뉴코드
	NUM_SERIAL	NUMBER(8) NOT NULL,				-- 글 번호
	NUM_GROUP	NUMBER(8) NOT NULL,				-- 글 그룹
	NUM_STEP	NUMBER(8) DEFAULT 0 NOT NULL,			-- 글 그룹 내의 순서
	NUM_DEPTH	NUMBER(1) DEFAULT 0 NOT NULL,			-- 글 그룹 내의 들여쓰기
	STR_USER	VARCHAR2(15),					-- 로그인 후 글쓸대 회원 아이디
	STR_NAME	VARCHAR2(20) NOT NULL,				-- 이름
	STR_PASS	VARCHAR2(8) NOT NULL,				-- 패스워드
	STR_EMAIL	VARCHAR2(30),					-- 이메일
	STR_TITLE	VARCHAR2(60) NOT NULL,				-- 제목
	STR_TEXT1	VARCHAR2(4000) NOT NULL,			-- 글 내용 첫번째
	STR_TEXT2	VARCHAR2(4000),					-- 글 내용 두번째
	STR_TEXT3	VARCHAR2(4000),					-- 글 내용 세번째
	CHR_HTML	CHAR(1) DEFAULT 'Y' NOT NULL,			-- HTML 사용여부
	DT_DATE		DATE DEFAULT SYSDATE,				-- 등록일자
	NUM_HIT		NUMBER(8) DEFAULT 0 NOT NULL,			-- 조회수
	NUM_COMMENT	NUMBER(8) DEFAULT 0 NOT NULL,			-- 코멘트 갯수 (매번 count(*) from 코멘트테이블 할수는 없다)
	NUM_FILE	NUMBER(2) DEFAULT 0 NOT NULL,			-- 파일개수 ( 파일의 갯수가 0일때 파일테이블을 CALL하지 않는다 )
	STR_IP		VARCHAR2(15) NOT NULL,				-- 아이피
	CHR_TYPE	CHAR(1) DEFAULT 'B' NOT NULL,			-- 게시물 타잎 (겔러리 G, 게시판 B)
	STR_THUMB	VARCHAR2(100),					-- 썸네일 이미지

	CONSTRAINT PK_TAB_BOARD
	PRIMARY KEY (NUM_OID,NUM_MCODE,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;


CREATE INDEX IDX_TAB_BOARD_SEARCH
    ON TAB_BOARD (NUM_OID,NUM_MCODE,NUM_GROUP,NUM_STEP,STR_NAME,STR_TITLE) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

CREATE INDEX IDX_TAB_BOARD_ALL
    ON TAB_BOARD (NUM_OID,DT_DATE,CHR_TYPE,NUM_MCODE) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

CREATE INDEX IDX_TAB_BOARD_DEPTH
    ON TAB_BOARD (NUM_OID,NUM_MCODE,NUM_GROUP,NUM_STEP,NUM_DEPTH,STR_NAME,STR_TITLE) 
    TABLESPACE TS_ACADEMY_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

-- 게시판 설정

CREATE TABLE TAB_BOARD_CONFIG (
	NUM_OID		NUMBER(8) NOT NULL,		-- 학교구분
	NUM_MCODE	NUMBER(8) NOT NULL,		-- 메뉴코드
	STR_TITLE	VARCHAR2(255) DEFAULT '게시판' NOT NULL,		-- 게시판 타이틀
	STR_SKIN	VARCHAR2(20) DEFAULT 'default' NOT NULL,		-- 게시판 스킨
	NUM_LISTNUM	NUMBER(8) DEFAULT 10 NOT NULL,	-- 목록 표시줄수
	NUM_NAVNUM	NUMBER(8) DEFAULT 10 NOT NULL,	-- 페이징 표시갯수
	NUM_TITLELEN	NUMBER(8) DEFAULT 200 NOT NULL,	-- 타이틀바 길이(바이트)
	CHR_LISTTYPE	CHAR(1) DEFAULT 'B' NOT NULL,	-- 리스팅형태 (B 게시판형, G 겔러리형)
	CHR_ODDCOLOR	CHAR(7) DEFAULT '#FFFFFF' NOT NULL,	-- 홀수열 색상
	CHR_EVENCOLOR	CHAR(7) DEFAULT '#FFFFFF' NOT NULL,	-- 짝수열 색상
	CHR_COMMENT	CHAR(1) DEFAULT 'Y' NOT NULL,
	CHR_RECENT	CHAR(1) DEFAULT 'N' NOT NULL,

	CONSTRAINT PK_TAB_BOARD_CONFIG
	PRIMARY KEY (NUM_OID,NUM_MCODE)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;

-- 게시판 한줄 글쓰기

CREATE TABLE TAB_BOARD_COMMENT(
	NUM_OID		NUMBER(8) NOT NULL,		-- 학교구분
	NUM_MCODE	NUMBER(8) NOT NULL,		-- 메뉴코드
	NUM_MAIN	NUMBER(8) NOT NULL,		-- 글 번호( TAB_BOARD의 NUM_SERIAL과 매칭 )
	NUM_SERIAL	NUMBER(8) NOT NULL,		-- 이 테이블의 글 번호
	STR_USER	VARCHAR2(15),			-- 로그인 후 글쓸때 회원 아이디
	STR_NAME	VARCHAR2(20) DEFAULT 'GUEST' NOT NULL,
	STR_PASS	VARCHAR2(8) DEFAULT '1111' NOT NULL,
	STR_COMMENT	VARCHAR2(150) NOT NULL,
	DT_DATE		DATE DEFAULT SYSDATE,
	STR_IP		VARCHAR2(15) NOT NULL,				-- 아이피

	CONSTRAINT PK_TAB_BOARD_COMMENT
	PRIMARY KEY (NUM_OID,NUM_MCODE,NUM_MAIN,NUM_SERIAL)
	USING INDEX 
	TABLESPACE TS_ACADEMY_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_ACADEMY_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;



























--
-- 지사, 가맹기관 정보
--
CREATE TABLE TAB_BRANCH (
	NUM_BID     NUMBER(8)      NOT NULL,	-- 본사번호
	NUM_PARENT  NUMBER(8)      NOT NULL,	-- 상위기관번호
	NUM_OID     NUMBER(8)      NOT NULL,	-- 기관번호
	STR_BRANCHID VARCHAR2(20),				-- 지사아이디
	STR_TITLE   VARCHAR2(200)  NOT NULL,	-- 기관명
	DT_DATE     DATE           DEFAULT SYSDATE NOT NULL,
	DT_PAYDATE  DATE           DEFAULT SYSDATE,
	CHR_STATUS  CHAR(1)        DEFAULT 'A'     NOT NULL,
	CONSTRAINT PK_TAB_TAB_BRANCH
	PRIMARY KEY (NUM_BID, NUM_OID)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE;


-- 지사별 목록 출력용
CREATE INDEX IDX_TAB_BRANCH
    ON TAB_BRANCH (STR_BRANCHID, NUM_OID)
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

-- 내 본사 찾기용
CREATE INDEX IDX_TAB_BRANCH_REV
    ON TAB_BRANCH (NUM_OID, NUM_BID)
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;

--
-- 학원 개설 강좌
--
CREATE TABLE TAB_LECTURE (
	NUM_OID                 NUMBER(8) NOT NULL,
	STR_LCODE               VARCHAR2(50) NOT NULL,          -- 강좌번호(INDEX KEY)
	STR_SUBJECT             VARCHAR2(50),                    -- 강좌명
	STR_SCHD_TIME           VARCHAR2(200),                   -- 강의시간("월 10 00 ~ 11 00<br>....")
	STR_PLACE               VARCHAR2(50),                    -- 장소
	STR_TARGET              VARCHAR2(50),                    -- 대상
	NUM_PRICE               NUMBER(12) DEFAULT '0' NOT NULL,-- 수강료
	NUM_CAPACITY            NUMBER(4) DEFAULT '0' NOT NULL, -- 수강정원
	NUM_REG_CNT             NUMBER(4) DEFAULT '0' NOT NULL, -- 현재수강인원(등록할 때마다 하나씩 올라감)
	STR_TEACHER             VARCHAR2(16),                    -- 강사명
	CHR_ENABLED             CHAR(1),                        -- 사용가능여부
	DT_WDATE                DATE DEFAULT SYSDATE,           -- 등록일

	CONSTRAINT PK_TAB_LECTURE
	PRIMARY KEY (NUM_OID,STR_LCODE)
	USING INDEX
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

--
-- 수강신청 테이블
--
CREATE TABLE TAB_PASSROAD_REGISTER (
	NUM_OID		NUMBER(8) NOT NULL,
	STR_ID		VARCHAR2(15) NOT NULL,				-- 회원 ID
	CHR_LTYPE	CHAR(1) DEFAULT 'L' NOT NULL,
	STR_CODE	VARCHAR2(50) DEFAULT 0,				-- 강좌코드(온라인,오프라인)
	STR_TITLE	VARCHAR2(255) DEFAULT 1 NOT NULL,		-- 강좌명
	STR_NAME	VARCHAR2(16),					-- 회원이름
	STR_PAY_TYPE	VARCHAR2(10) DEFAULT 'card' NOT NULL,		-- 결제방법
	NUM_PRICE       NUMBER(12) DEFAULT '0' NOT NULL,		-- 수강료
	ORDER_ID	VARCHAR2(64) NOT NULL,				-- TAB_PASSROAD_PAYMENT.ORDER_ID
	DT_SDATE	DATE NOT NULL,					-- 강좌 시작일
	DT_EDATE	DATE NOT NULL,					-- 강좌 마감일
	DT_WDATE	DATE DEFAULT SYSDATE,				-- 등록일

	CONSTRAINT PK_TAB_PASSROAD_REGISTER
	PRIMARY KEY (NUM_OID, STR_ID, STR_CODE)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

--
-- 결제 테이블
--
CREATE TABLE TAB_PASSROAD_PAYMENT (
	ORDER_ID                VARCHAR2(64) NOT NULL,   -- CYBERPASS의 OID(주문번호 YYYmmddHHiiss-{{str_p_id}})
	TRXID                   VARCHAR2(24),            -- 거래번호(거래번호가 없다면 결제를 하지 않은경우)
	NUM_OID                 NUMBER(8) NOT NULL,
	STR_ID                  VARCHAR2(15) NOT NULL,   -- 결제자 ID
	STR_NAME                VARCHAR2(20) NOT NULL,   -- 결제자 이름
	PAY_TYPE                VARCHAR2(10) NOT NULL,   -- 결제방법
	STR_ITEMS               VARCHAR2(200) NOT NULL,  -- 구매한 상품코드
	NUM_PRICE               NUMBER(12) NOT NULL,    -- 결제금액

	EXTRA_DATA              VARCHAR2(4000),          -- 기타 데이타(serialize Data)

	RESULT_CODE             CHAR(4),                -- 결과코드
	RESULT                  NUMBER(1),              -- 결제성공여부
	ERRMSG                  VARCHAR2(10),            -- 에러메시지
	DT_WDATE                DATE DEFAULT SYSDATE,   -- 등록일

	CONSTRAINT PK_TAB_PASSROAD_PAYMENT
	PRIMARY KEY (ORDER_ID)
	USING INDEX
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;


--
-- 서비스테이블
--
CREATE TABLE TAB_PASSROAD_SERVICE (
	NUM_OID		NUMBER(8) NOT NULL,
	STR_ID			VARCHAR2(20) NOT NULL,
	STR_GOODS_CODE	VARCHAR2(50) NOT NULL,		-- 상품코드(강좌코드)
	STR_GOODS_NAME	VARCHAR2(255) NOT NULL,		-- 상품명(강좌명)
	DT_START	DATE NOT NULL,					-- 서비스 시작일
	DT_END		DATE NOT NULL,					-- 서비스 종료일
	CHR_LTYPE	CHAR(1) DEFAULT 'L' NOT NULL,	-- 강좌타잎 (L = 온라인, O = 오프라인)

	CONSTRAINT PK_TAB_PASSROAD_SERVICE
	PRIMARY KEY (NUM_OID, STR_GOODS_CODE)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

CREATE INDEX IDX_TAB_PASSROAD_SERVICE
    ON TAB_PASSROAD_SERVICE (NUM_OID, STR_ID, DT_START, DT_END, STR_GOODS_CODE) 
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;


-- 
-- 추가적인 회원관리 (기관별로 유일, 
-- 
CREATE TABLE TAB_ADDITIONAL_MEMBER (
	NUM_OID		NUMBER(8) NOT NULL,
	STR_GROUP	VARCHAR2(20) DEFAULT '-' NOT NULL,
	STR_ID		VARCHAR2(20) NOT NULL,
	STR_PASS	VARCHAR2(20) NOT NULL,
	STR_NAME	VARCHAR2(50) NOT NULL,
	STR_DESCRIPTION VARCHAR2(4000) NOT NULL,

	CONSTRAINT PK_TAB_ADDITIONAL_MEMBER
	PRIMARY KEY (NUM_OID, STR_ID)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;



--
-- 온라인 컨텐츠
--
CREATE TABLE TAB_ONLINE_CONTENT ( 
	NUM_OID		NUMBER(8) NOT NULL,
	STR_CPCODE	VARCHAR2(50) DEFAULT 1 NOT NULL,		-- 강좌코드
	STR_TITLE	VARCHAR2(255) DEFAULT 1 NOT NULL,		-- 강좌명
	CHR_CTYPE	CHAR(1) DEFAULT 'S' NOT NULL,			-- /* 'S' for 'single', 'M' for 'multiple' */
	NUM_TARGET	NUMBER(8) DEFAULT 0 NOT NULL,			-- /* 1 초등 2 중등 4 고등 */
	STR_CONSTITUENT	VARCHAR2(255),						-- 강좌구성 
	NUM_PRICE	NUMBER(8) DEFAULT 0 NOT NULL,			-- 가격
	NUM_CONSUMER_PRICE NUMBER(8) DEFAULT 0 NOT NULL,	-- 소비자 가격

	STR_PICTURE VARCHAR2(255),							-- 강좌 이미지 ??

	STR_INTRO1	VARCHAR2(4000),		-- 강좌소개
	STR_INTRO2	VARCHAR2(4000),		-- 강좌소개
	STR_INTRO3	VARCHAR2(4000),		-- 강좌소개

	STR_CURRICULUM1	VARCHAR2(4000),	-- 커리큘럼
	STR_CURRICULUM2	VARCHAR2(4000),	-- 커리큘럼
	STR_CURRICULUM3	VARCHAR2(4000),	-- 커리큘럼

	STR_TEACHER_NAME VARCHAR2(100), -- 강사이름
	STR_TEACHER1	VARCHAR2(4000),	-- 강사소개
	STR_TEACHER2	VARCHAR2(4000),	-- 강사소개
	STR_TEACHER3	VARCHAR2(4000),	-- 강사소개

	STR_MATERIAL	VARCHAR2(4000),	-- 교재선택정보
	STR_MATERIAL_INFO	VARCHAR2(4000),	-- 교재소개

	CONSTRAINT PK_TAB_ONLINE_CONTENT
	PRIMARY KEY (NUM_OID, STR_CPCODE)
	USING INDEX 
	TABLESPACE TS_PASSLOAD_I
	STORAGE(INITIAL 512K NEXT 512K)
) TABLESPACE TS_PASSLOAD_D STORAGE(INITIAL 1024K NEXT 1024K) NOCACHE ;

CREATE INDEX IDX_TAB_ONLINE_CONTENT
    ON TAB_ONLINE_CONTENT (NUM_OID, CHR_CTYPE) 
    TABLESPACE TS_PASSLOAD_I PCTFREE 10 INITRANS 2 MAXTRANS 255 
    STORAGE ( INITIAL 512K NEXT 512K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    NOLOGGING ;
